/**
 * 路由参数键（对齐公司 RouterKeys 枚举）
 */
export class RouterKeys {
  static readonly URL: string = 'url'
  static readonly TITLE: string = 'title'
  static readonly SHOW_TITLE: string = 'showTitle'
  static readonly SHOW_PROGRESS: string = 'showProgress'
  static readonly SCENE: string = 'scene'
  static readonly BRIDGE_PROFILE: string = 'bridgeProfile'
  static readonly MULTI: string = 'multi'
  static readonly USE_OVERLAY: string = 'useOverlay'
  static readonly SOURCE: string = 'source'
  static readonly NEED_ENCODE_PARAMS: string = 'needEncodeParams'
}
